name: Daily Workflow

on:
  schedule:
    - cron: "5 5 1-26 12 *"

jobs:
  create-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "Github Actions"

      - name: Download input
        run: |
          day=$(date +%d)
          url_day=$(echo $day | sed 's/^0*//')
          mkdir -p src/${day}
          curl --cookie "session=${SESSION}" \
            -o src/${day}/input.txt \
            "https://adventofcode.com/2022/day/${url_day}/input"
          truncate -s -1 src/${day}/input.txt
        env:
          SESSION: ${{ secrets.AOC_SESSION_COOKIE }}

      - name: Commit and push files
        run: |
          git add .
          git commit -m "Adding todays files"
          git push
